// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Base is the predicate function for base builders.
type Base func(*sql.Selector)

// BaseInfo is the predicate function for baseinfo builders.
type BaseInfo func(*sql.Selector)

// BaseMember is the predicate function for basemember builders.
type BaseMember func(*sql.Selector)

// BaseNavState is the predicate function for basenavstate builders.
type BaseNavState func(*sql.Selector)
