// Code generated by ent, DO NOT EDIT.

package entity

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"mai.today/core/entity/basemember"
)

// BaseMemberCreate is the builder for creating a BaseMember entity.
type BaseMemberCreate struct {
	config
	mutation *BaseMemberMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (bmc *BaseMemberCreate) SetCreatedAt(t time.Time) *BaseMemberCreate {
	bmc.mutation.SetCreatedAt(t)
	return bmc
}

// SetDeletedAt sets the "deleted_at" field.
func (bmc *BaseMemberCreate) SetDeletedAt(t time.Time) *BaseMemberCreate {
	bmc.mutation.SetDeletedAt(t)
	return bmc
}

// SetUpdatedAt sets the "updated_at" field.
func (bmc *BaseMemberCreate) SetUpdatedAt(t time.Time) *BaseMemberCreate {
	bmc.mutation.SetUpdatedAt(t)
	return bmc
}

// SetBaseID sets the "base_id" field.
func (bmc *BaseMemberCreate) SetBaseID(s string) *BaseMemberCreate {
	bmc.mutation.SetBaseID(s)
	return bmc
}

// SetUserID sets the "user_id" field.
func (bmc *BaseMemberCreate) SetUserID(s string) *BaseMemberCreate {
	bmc.mutation.SetUserID(s)
	return bmc
}

// SetID sets the "id" field.
func (bmc *BaseMemberCreate) SetID(s string) *BaseMemberCreate {
	bmc.mutation.SetID(s)
	return bmc
}

// Mutation returns the BaseMemberMutation object of the builder.
func (bmc *BaseMemberCreate) Mutation() *BaseMemberMutation {
	return bmc.mutation
}

// Save creates the BaseMember in the database.
func (bmc *BaseMemberCreate) Save(ctx context.Context) (*BaseMember, error) {
	return withHooks(ctx, bmc.sqlSave, bmc.mutation, bmc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (bmc *BaseMemberCreate) SaveX(ctx context.Context) *BaseMember {
	v, err := bmc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bmc *BaseMemberCreate) Exec(ctx context.Context) error {
	_, err := bmc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bmc *BaseMemberCreate) ExecX(ctx context.Context) {
	if err := bmc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bmc *BaseMemberCreate) check() error {
	if _, ok := bmc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`entity: missing required field "BaseMember.created_at"`)}
	}
	if _, ok := bmc.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`entity: missing required field "BaseMember.deleted_at"`)}
	}
	if _, ok := bmc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`entity: missing required field "BaseMember.updated_at"`)}
	}
	if _, ok := bmc.mutation.BaseID(); !ok {
		return &ValidationError{Name: "base_id", err: errors.New(`entity: missing required field "BaseMember.base_id"`)}
	}
	if _, ok := bmc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`entity: missing required field "BaseMember.user_id"`)}
	}
	return nil
}

func (bmc *BaseMemberCreate) sqlSave(ctx context.Context) (*BaseMember, error) {
	if err := bmc.check(); err != nil {
		return nil, err
	}
	_node, _spec := bmc.createSpec()
	if err := sqlgraph.CreateNode(ctx, bmc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected BaseMember.ID type: %T", _spec.ID.Value)
		}
	}
	bmc.mutation.id = &_node.ID
	bmc.mutation.done = true
	return _node, nil
}

func (bmc *BaseMemberCreate) createSpec() (*BaseMember, *sqlgraph.CreateSpec) {
	var (
		_node = &BaseMember{config: bmc.config}
		_spec = sqlgraph.NewCreateSpec(basemember.Table, sqlgraph.NewFieldSpec(basemember.FieldID, field.TypeString))
	)
	if id, ok := bmc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := bmc.mutation.CreatedAt(); ok {
		_spec.SetField(basemember.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := bmc.mutation.DeletedAt(); ok {
		_spec.SetField(basemember.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := bmc.mutation.UpdatedAt(); ok {
		_spec.SetField(basemember.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := bmc.mutation.BaseID(); ok {
		_spec.SetField(basemember.FieldBaseID, field.TypeString, value)
		_node.BaseID = value
	}
	if value, ok := bmc.mutation.UserID(); ok {
		_spec.SetField(basemember.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	return _node, _spec
}

// BaseMemberCreateBulk is the builder for creating many BaseMember entities in bulk.
type BaseMemberCreateBulk struct {
	config
	err      error
	builders []*BaseMemberCreate
}

// Save creates the BaseMember entities in the database.
func (bmcb *BaseMemberCreateBulk) Save(ctx context.Context) ([]*BaseMember, error) {
	if bmcb.err != nil {
		return nil, bmcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(bmcb.builders))
	nodes := make([]*BaseMember, len(bmcb.builders))
	mutators := make([]Mutator, len(bmcb.builders))
	for i := range bmcb.builders {
		func(i int, root context.Context) {
			builder := bmcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BaseMemberMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, bmcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, bmcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, bmcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (bmcb *BaseMemberCreateBulk) SaveX(ctx context.Context) []*BaseMember {
	v, err := bmcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bmcb *BaseMemberCreateBulk) Exec(ctx context.Context) error {
	_, err := bmcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bmcb *BaseMemberCreateBulk) ExecX(ctx context.Context) {
	if err := bmcb.Exec(ctx); err != nil {
		panic(err)
	}
}
