// Code generated by ent, DO NOT EDIT.

package entity

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"mai.today/core/entity/basenavstate"
)

// BaseNavStateCreate is the builder for creating a BaseNavState entity.
type BaseNavStateCreate struct {
	config
	mutation *BaseNavStateMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (bnsc *BaseNavStateCreate) SetCreatedAt(t time.Time) *BaseNavStateCreate {
	bnsc.mutation.SetCreatedAt(t)
	return bnsc
}

// SetDeletedAt sets the "deleted_at" field.
func (bnsc *BaseNavStateCreate) SetDeletedAt(t time.Time) *BaseNavStateCreate {
	bnsc.mutation.SetDeletedAt(t)
	return bnsc
}

// SetUpdatedAt sets the "updated_at" field.
func (bnsc *BaseNavStateCreate) SetUpdatedAt(t time.Time) *BaseNavStateCreate {
	bnsc.mutation.SetUpdatedAt(t)
	return bnsc
}

// SetBaseID sets the "base_id" field.
func (bnsc *BaseNavStateCreate) SetBaseID(s string) *BaseNavStateCreate {
	bnsc.mutation.SetBaseID(s)
	return bnsc
}

// SetUserID sets the "user_id" field.
func (bnsc *BaseNavStateCreate) SetUserID(s string) *BaseNavStateCreate {
	bnsc.mutation.SetUserID(s)
	return bnsc
}

// SetIndex sets the "index" field.
func (bnsc *BaseNavStateCreate) SetIndex(i int) *BaseNavStateCreate {
	bnsc.mutation.SetIndex(i)
	return bnsc
}

// SetID sets the "id" field.
func (bnsc *BaseNavStateCreate) SetID(s string) *BaseNavStateCreate {
	bnsc.mutation.SetID(s)
	return bnsc
}

// Mutation returns the BaseNavStateMutation object of the builder.
func (bnsc *BaseNavStateCreate) Mutation() *BaseNavStateMutation {
	return bnsc.mutation
}

// Save creates the BaseNavState in the database.
func (bnsc *BaseNavStateCreate) Save(ctx context.Context) (*BaseNavState, error) {
	return withHooks(ctx, bnsc.sqlSave, bnsc.mutation, bnsc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (bnsc *BaseNavStateCreate) SaveX(ctx context.Context) *BaseNavState {
	v, err := bnsc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bnsc *BaseNavStateCreate) Exec(ctx context.Context) error {
	_, err := bnsc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bnsc *BaseNavStateCreate) ExecX(ctx context.Context) {
	if err := bnsc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bnsc *BaseNavStateCreate) check() error {
	if _, ok := bnsc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`entity: missing required field "BaseNavState.created_at"`)}
	}
	if _, ok := bnsc.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`entity: missing required field "BaseNavState.deleted_at"`)}
	}
	if _, ok := bnsc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`entity: missing required field "BaseNavState.updated_at"`)}
	}
	if _, ok := bnsc.mutation.BaseID(); !ok {
		return &ValidationError{Name: "base_id", err: errors.New(`entity: missing required field "BaseNavState.base_id"`)}
	}
	if _, ok := bnsc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`entity: missing required field "BaseNavState.user_id"`)}
	}
	if _, ok := bnsc.mutation.Index(); !ok {
		return &ValidationError{Name: "index", err: errors.New(`entity: missing required field "BaseNavState.index"`)}
	}
	return nil
}

func (bnsc *BaseNavStateCreate) sqlSave(ctx context.Context) (*BaseNavState, error) {
	if err := bnsc.check(); err != nil {
		return nil, err
	}
	_node, _spec := bnsc.createSpec()
	if err := sqlgraph.CreateNode(ctx, bnsc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected BaseNavState.ID type: %T", _spec.ID.Value)
		}
	}
	bnsc.mutation.id = &_node.ID
	bnsc.mutation.done = true
	return _node, nil
}

func (bnsc *BaseNavStateCreate) createSpec() (*BaseNavState, *sqlgraph.CreateSpec) {
	var (
		_node = &BaseNavState{config: bnsc.config}
		_spec = sqlgraph.NewCreateSpec(basenavstate.Table, sqlgraph.NewFieldSpec(basenavstate.FieldID, field.TypeString))
	)
	if id, ok := bnsc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := bnsc.mutation.CreatedAt(); ok {
		_spec.SetField(basenavstate.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := bnsc.mutation.DeletedAt(); ok {
		_spec.SetField(basenavstate.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := bnsc.mutation.UpdatedAt(); ok {
		_spec.SetField(basenavstate.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := bnsc.mutation.BaseID(); ok {
		_spec.SetField(basenavstate.FieldBaseID, field.TypeString, value)
		_node.BaseID = value
	}
	if value, ok := bnsc.mutation.UserID(); ok {
		_spec.SetField(basenavstate.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := bnsc.mutation.Index(); ok {
		_spec.SetField(basenavstate.FieldIndex, field.TypeInt, value)
		_node.Index = value
	}
	return _node, _spec
}

// BaseNavStateCreateBulk is the builder for creating many BaseNavState entities in bulk.
type BaseNavStateCreateBulk struct {
	config
	err      error
	builders []*BaseNavStateCreate
}

// Save creates the BaseNavState entities in the database.
func (bnscb *BaseNavStateCreateBulk) Save(ctx context.Context) ([]*BaseNavState, error) {
	if bnscb.err != nil {
		return nil, bnscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(bnscb.builders))
	nodes := make([]*BaseNavState, len(bnscb.builders))
	mutators := make([]Mutator, len(bnscb.builders))
	for i := range bnscb.builders {
		func(i int, root context.Context) {
			builder := bnscb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BaseNavStateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, bnscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, bnscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, bnscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (bnscb *BaseNavStateCreateBulk) SaveX(ctx context.Context) []*BaseNavState {
	v, err := bnscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bnscb *BaseNavStateCreateBulk) Exec(ctx context.Context) error {
	_, err := bnscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bnscb *BaseNavStateCreateBulk) ExecX(ctx context.Context) {
	if err := bnscb.Exec(ctx); err != nil {
		panic(err)
	}
}
