// Code generated by ent, DO NOT EDIT.

package entity

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"mai.today/core/entity/basemember"
	"mai.today/core/entity/predicate"
)

// BaseMemberQuery is the builder for querying BaseMember entities.
type BaseMemberQuery struct {
	config
	ctx        *QueryContext
	order      []basemember.OrderOption
	inters     []Interceptor
	predicates []predicate.BaseMember
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BaseMemberQuery builder.
func (bmq *BaseMemberQuery) Where(ps ...predicate.BaseMember) *BaseMemberQuery {
	bmq.predicates = append(bmq.predicates, ps...)
	return bmq
}

// Limit the number of records to be returned by this query.
func (bmq *BaseMemberQuery) Limit(limit int) *BaseMemberQuery {
	bmq.ctx.Limit = &limit
	return bmq
}

// Offset to start from.
func (bmq *BaseMemberQuery) Offset(offset int) *BaseMemberQuery {
	bmq.ctx.Offset = &offset
	return bmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (bmq *BaseMemberQuery) Unique(unique bool) *BaseMemberQuery {
	bmq.ctx.Unique = &unique
	return bmq
}

// Order specifies how the records should be ordered.
func (bmq *BaseMemberQuery) Order(o ...basemember.OrderOption) *BaseMemberQuery {
	bmq.order = append(bmq.order, o...)
	return bmq
}

// First returns the first BaseMember entity from the query.
// Returns a *NotFoundError when no BaseMember was found.
func (bmq *BaseMemberQuery) First(ctx context.Context) (*BaseMember, error) {
	nodes, err := bmq.Limit(1).All(setContextOp(ctx, bmq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{basemember.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (bmq *BaseMemberQuery) FirstX(ctx context.Context) *BaseMember {
	node, err := bmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first BaseMember ID from the query.
// Returns a *NotFoundError when no BaseMember ID was found.
func (bmq *BaseMemberQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = bmq.Limit(1).IDs(setContextOp(ctx, bmq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{basemember.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (bmq *BaseMemberQuery) FirstIDX(ctx context.Context) string {
	id, err := bmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single BaseMember entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one BaseMember entity is found.
// Returns a *NotFoundError when no BaseMember entities are found.
func (bmq *BaseMemberQuery) Only(ctx context.Context) (*BaseMember, error) {
	nodes, err := bmq.Limit(2).All(setContextOp(ctx, bmq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{basemember.Label}
	default:
		return nil, &NotSingularError{basemember.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (bmq *BaseMemberQuery) OnlyX(ctx context.Context) *BaseMember {
	node, err := bmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only BaseMember ID in the query.
// Returns a *NotSingularError when more than one BaseMember ID is found.
// Returns a *NotFoundError when no entities are found.
func (bmq *BaseMemberQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = bmq.Limit(2).IDs(setContextOp(ctx, bmq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{basemember.Label}
	default:
		err = &NotSingularError{basemember.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (bmq *BaseMemberQuery) OnlyIDX(ctx context.Context) string {
	id, err := bmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of BaseMembers.
func (bmq *BaseMemberQuery) All(ctx context.Context) ([]*BaseMember, error) {
	ctx = setContextOp(ctx, bmq.ctx, "All")
	if err := bmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*BaseMember, *BaseMemberQuery]()
	return withInterceptors[[]*BaseMember](ctx, bmq, qr, bmq.inters)
}

// AllX is like All, but panics if an error occurs.
func (bmq *BaseMemberQuery) AllX(ctx context.Context) []*BaseMember {
	nodes, err := bmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of BaseMember IDs.
func (bmq *BaseMemberQuery) IDs(ctx context.Context) (ids []string, err error) {
	if bmq.ctx.Unique == nil && bmq.path != nil {
		bmq.Unique(true)
	}
	ctx = setContextOp(ctx, bmq.ctx, "IDs")
	if err = bmq.Select(basemember.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (bmq *BaseMemberQuery) IDsX(ctx context.Context) []string {
	ids, err := bmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (bmq *BaseMemberQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, bmq.ctx, "Count")
	if err := bmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, bmq, querierCount[*BaseMemberQuery](), bmq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (bmq *BaseMemberQuery) CountX(ctx context.Context) int {
	count, err := bmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (bmq *BaseMemberQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, bmq.ctx, "Exist")
	switch _, err := bmq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("entity: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (bmq *BaseMemberQuery) ExistX(ctx context.Context) bool {
	exist, err := bmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BaseMemberQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (bmq *BaseMemberQuery) Clone() *BaseMemberQuery {
	if bmq == nil {
		return nil
	}
	return &BaseMemberQuery{
		config:     bmq.config,
		ctx:        bmq.ctx.Clone(),
		order:      append([]basemember.OrderOption{}, bmq.order...),
		inters:     append([]Interceptor{}, bmq.inters...),
		predicates: append([]predicate.BaseMember{}, bmq.predicates...),
		// clone intermediate query.
		sql:  bmq.sql.Clone(),
		path: bmq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BaseMember.Query().
//		GroupBy(basemember.FieldCreatedAt).
//		Aggregate(entity.Count()).
//		Scan(ctx, &v)
func (bmq *BaseMemberQuery) GroupBy(field string, fields ...string) *BaseMemberGroupBy {
	bmq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BaseMemberGroupBy{build: bmq}
	grbuild.flds = &bmq.ctx.Fields
	grbuild.label = basemember.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.BaseMember.Query().
//		Select(basemember.FieldCreatedAt).
//		Scan(ctx, &v)
func (bmq *BaseMemberQuery) Select(fields ...string) *BaseMemberSelect {
	bmq.ctx.Fields = append(bmq.ctx.Fields, fields...)
	sbuild := &BaseMemberSelect{BaseMemberQuery: bmq}
	sbuild.label = basemember.Label
	sbuild.flds, sbuild.scan = &bmq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BaseMemberSelect configured with the given aggregations.
func (bmq *BaseMemberQuery) Aggregate(fns ...AggregateFunc) *BaseMemberSelect {
	return bmq.Select().Aggregate(fns...)
}

func (bmq *BaseMemberQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range bmq.inters {
		if inter == nil {
			return fmt.Errorf("entity: uninitialized interceptor (forgotten import entity/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, bmq); err != nil {
				return err
			}
		}
	}
	for _, f := range bmq.ctx.Fields {
		if !basemember.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("entity: invalid field %q for query", f)}
		}
	}
	if bmq.path != nil {
		prev, err := bmq.path(ctx)
		if err != nil {
			return err
		}
		bmq.sql = prev
	}
	return nil
}

func (bmq *BaseMemberQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*BaseMember, error) {
	var (
		nodes = []*BaseMember{}
		_spec = bmq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*BaseMember).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &BaseMember{config: bmq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, bmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (bmq *BaseMemberQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := bmq.querySpec()
	_spec.Node.Columns = bmq.ctx.Fields
	if len(bmq.ctx.Fields) > 0 {
		_spec.Unique = bmq.ctx.Unique != nil && *bmq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, bmq.driver, _spec)
}

func (bmq *BaseMemberQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(basemember.Table, basemember.Columns, sqlgraph.NewFieldSpec(basemember.FieldID, field.TypeString))
	_spec.From = bmq.sql
	if unique := bmq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if bmq.path != nil {
		_spec.Unique = true
	}
	if fields := bmq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, basemember.FieldID)
		for i := range fields {
			if fields[i] != basemember.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := bmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := bmq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := bmq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := bmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (bmq *BaseMemberQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(bmq.driver.Dialect())
	t1 := builder.Table(basemember.Table)
	columns := bmq.ctx.Fields
	if len(columns) == 0 {
		columns = basemember.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if bmq.sql != nil {
		selector = bmq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if bmq.ctx.Unique != nil && *bmq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range bmq.predicates {
		p(selector)
	}
	for _, p := range bmq.order {
		p(selector)
	}
	if offset := bmq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := bmq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BaseMemberGroupBy is the group-by builder for BaseMember entities.
type BaseMemberGroupBy struct {
	selector
	build *BaseMemberQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (bmgb *BaseMemberGroupBy) Aggregate(fns ...AggregateFunc) *BaseMemberGroupBy {
	bmgb.fns = append(bmgb.fns, fns...)
	return bmgb
}

// Scan applies the selector query and scans the result into the given value.
func (bmgb *BaseMemberGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bmgb.build.ctx, "GroupBy")
	if err := bmgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BaseMemberQuery, *BaseMemberGroupBy](ctx, bmgb.build, bmgb, bmgb.build.inters, v)
}

func (bmgb *BaseMemberGroupBy) sqlScan(ctx context.Context, root *BaseMemberQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(bmgb.fns))
	for _, fn := range bmgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*bmgb.flds)+len(bmgb.fns))
		for _, f := range *bmgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*bmgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bmgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BaseMemberSelect is the builder for selecting fields of BaseMember entities.
type BaseMemberSelect struct {
	*BaseMemberQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (bms *BaseMemberSelect) Aggregate(fns ...AggregateFunc) *BaseMemberSelect {
	bms.fns = append(bms.fns, fns...)
	return bms
}

// Scan applies the selector query and scans the result into the given value.
func (bms *BaseMemberSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bms.ctx, "Select")
	if err := bms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BaseMemberQuery, *BaseMemberSelect](ctx, bms.BaseMemberQuery, bms, bms.inters, v)
}

func (bms *BaseMemberSelect) sqlScan(ctx context.Context, root *BaseMemberQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(bms.fns))
	for _, fn := range bms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*bms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
