// Code generated by ent, DO NOT EDIT.

package entity

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"mai.today/core/entity/baseinfo"
)

// BaseInfo is the model entity for the BaseInfo schema.
type BaseInfo struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty" bson:"_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// BaseID holds the value of the "base_id" field.
	BaseID string `json:"base_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Logo holds the value of the "logo" field.
	Logo string `json:"logo,omitempty"`
	// Color holds the value of the "color" field.
	Color        string `json:"color,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BaseInfo) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case baseinfo.FieldID, baseinfo.FieldBaseID, baseinfo.FieldName, baseinfo.FieldLogo, baseinfo.FieldColor:
			values[i] = new(sql.NullString)
		case baseinfo.FieldCreatedAt, baseinfo.FieldDeletedAt, baseinfo.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BaseInfo fields.
func (bi *BaseInfo) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case baseinfo.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				bi.ID = value.String
			}
		case baseinfo.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				bi.CreatedAt = value.Time
			}
		case baseinfo.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				bi.DeletedAt = new(time.Time)
				*bi.DeletedAt = value.Time
			}
		case baseinfo.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				bi.UpdatedAt = value.Time
			}
		case baseinfo.FieldBaseID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field base_id", values[i])
			} else if value.Valid {
				bi.BaseID = value.String
			}
		case baseinfo.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				bi.Name = value.String
			}
		case baseinfo.FieldLogo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field logo", values[i])
			} else if value.Valid {
				bi.Logo = value.String
			}
		case baseinfo.FieldColor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field color", values[i])
			} else if value.Valid {
				bi.Color = value.String
			}
		default:
			bi.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BaseInfo.
// This includes values selected through modifiers, order, etc.
func (bi *BaseInfo) Value(name string) (ent.Value, error) {
	return bi.selectValues.Get(name)
}

// Update returns a builder for updating this BaseInfo.
// Note that you need to call BaseInfo.Unwrap() before calling this method if this BaseInfo
// was returned from a transaction, and the transaction was committed or rolled back.
func (bi *BaseInfo) Update() *BaseInfoUpdateOne {
	return NewBaseInfoClient(bi.config).UpdateOne(bi)
}

// Unwrap unwraps the BaseInfo entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (bi *BaseInfo) Unwrap() *BaseInfo {
	_tx, ok := bi.config.driver.(*txDriver)
	if !ok {
		panic("entity: BaseInfo is not a transactional entity")
	}
	bi.config.driver = _tx.drv
	return bi
}

// String implements the fmt.Stringer.
func (bi *BaseInfo) String() string {
	var builder strings.Builder
	builder.WriteString("BaseInfo(")
	builder.WriteString(fmt.Sprintf("id=%v, ", bi.ID))
	builder.WriteString("created_at=")
	builder.WriteString(bi.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := bi.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(bi.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("base_id=")
	builder.WriteString(bi.BaseID)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(bi.Name)
	builder.WriteString(", ")
	builder.WriteString("logo=")
	builder.WriteString(bi.Logo)
	builder.WriteString(", ")
	builder.WriteString("color=")
	builder.WriteString(bi.Color)
	builder.WriteByte(')')
	return builder.String()
}

// BaseInfos is a parsable slice of BaseInfo.
type BaseInfos []*BaseInfo
