// Code generated by ent, DO NOT EDIT.

package entity

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"mai.today/core/entity/basemember"
	"mai.today/core/entity/predicate"
)

// BaseMemberDelete is the builder for deleting a BaseMember entity.
type BaseMemberDelete struct {
	config
	hooks    []Hook
	mutation *BaseMemberMutation
}

// Where appends a list predicates to the BaseMemberDelete builder.
func (bmd *BaseMemberDelete) Where(ps ...predicate.BaseMember) *BaseMemberDelete {
	bmd.mutation.Where(ps...)
	return bmd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (bmd *BaseMemberDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, bmd.sqlExec, bmd.mutation, bmd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (bmd *BaseMemberDelete) ExecX(ctx context.Context) int {
	n, err := bmd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (bmd *BaseMemberDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(basemember.Table, sqlgraph.NewFieldSpec(basemember.FieldID, field.TypeString))
	if ps := bmd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, bmd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	bmd.mutation.done = true
	return affected, err
}

// BaseMemberDeleteOne is the builder for deleting a single BaseMember entity.
type BaseMemberDeleteOne struct {
	bmd *BaseMemberDelete
}

// Where appends a list predicates to the BaseMemberDelete builder.
func (bmdo *BaseMemberDeleteOne) Where(ps ...predicate.BaseMember) *BaseMemberDeleteOne {
	bmdo.bmd.mutation.Where(ps...)
	return bmdo
}

// Exec executes the deletion query.
func (bmdo *BaseMemberDeleteOne) Exec(ctx context.Context) error {
	n, err := bmdo.bmd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{basemember.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (bmdo *BaseMemberDeleteOne) ExecX(ctx context.Context) {
	if err := bmdo.Exec(ctx); err != nil {
		panic(err)
	}
}
