name: Deploy to Cloud Run from Source

on:
  push:
    branches:
      - CloudRun_louis

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate to Google Cloud
      id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/760527922880/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'
        service_account: '760527922880-compute@developer.gserviceaccount.com'
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Build and Push Image using Cloud Buildpacks
      run: |
        IMAGE_NAME=gcr.io/${{ secrets.GCP_PROJECT_ID }}/prod-maitoday-cloud-run
        gcloud builds submit --pack image=$IMAGE_NAME .

    - name: Deploy to Cloud Run
      run: |
        IMAGE_NAME=gcr.io/${{ secrets.GCP_PROJECT_ID }}/prod-maitoday-cloud-run
        gcloud run deploy prod-maitoday-cloud-run --image $IMAGE_NAME --platform managed --region us-central1 --project ${{ secrets.GCP_PROJECT_ID }} --update-labels managed-by=github-actions,commit-sha=${{ github.sha }}
