// Code generated by ent, DO NOT EDIT.

package basemember

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"mai.today/core/entity/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldEQ(FieldCreatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldEQ(FieldDeletedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldEQ(FieldUpdatedAt, v))
}

// BaseID applies equality check predicate on the "base_id" field. It's identical to BaseIDEQ.
func BaseID(v string) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldEQ(FieldBaseID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldEQ(FieldUserID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldLTE(FieldCreatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldLTE(FieldDeletedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldLTE(FieldUpdatedAt, v))
}

// BaseIDEQ applies the EQ predicate on the "base_id" field.
func BaseIDEQ(v string) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldEQ(FieldBaseID, v))
}

// BaseIDNEQ applies the NEQ predicate on the "base_id" field.
func BaseIDNEQ(v string) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldNEQ(FieldBaseID, v))
}

// BaseIDIn applies the In predicate on the "base_id" field.
func BaseIDIn(vs ...string) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldIn(FieldBaseID, vs...))
}

// BaseIDNotIn applies the NotIn predicate on the "base_id" field.
func BaseIDNotIn(vs ...string) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldNotIn(FieldBaseID, vs...))
}

// BaseIDGT applies the GT predicate on the "base_id" field.
func BaseIDGT(v string) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldGT(FieldBaseID, v))
}

// BaseIDGTE applies the GTE predicate on the "base_id" field.
func BaseIDGTE(v string) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldGTE(FieldBaseID, v))
}

// BaseIDLT applies the LT predicate on the "base_id" field.
func BaseIDLT(v string) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldLT(FieldBaseID, v))
}

// BaseIDLTE applies the LTE predicate on the "base_id" field.
func BaseIDLTE(v string) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldLTE(FieldBaseID, v))
}

// BaseIDContains applies the Contains predicate on the "base_id" field.
func BaseIDContains(v string) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldContains(FieldBaseID, v))
}

// BaseIDHasPrefix applies the HasPrefix predicate on the "base_id" field.
func BaseIDHasPrefix(v string) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldHasPrefix(FieldBaseID, v))
}

// BaseIDHasSuffix applies the HasSuffix predicate on the "base_id" field.
func BaseIDHasSuffix(v string) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldHasSuffix(FieldBaseID, v))
}

// BaseIDEqualFold applies the EqualFold predicate on the "base_id" field.
func BaseIDEqualFold(v string) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldEqualFold(FieldBaseID, v))
}

// BaseIDContainsFold applies the ContainsFold predicate on the "base_id" field.
func BaseIDContainsFold(v string) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldContainsFold(FieldBaseID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.BaseMember {
	return predicate.BaseMember(sql.FieldContainsFold(FieldUserID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BaseMember) predicate.BaseMember {
	return predicate.BaseMember(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BaseMember) predicate.BaseMember {
	return predicate.BaseMember(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BaseMember) predicate.BaseMember {
	return predicate.BaseMember(sql.NotPredicates(p))
}
