swagger: "2.0"
info:
    title: Mai.Today Server
    description: Mai.Today Server
    version: 1.0.0
host: localhost:8080
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /signin:
        post:
            tags:
                - authentication
            summary: 登入
            operationId: authentication#SignIn
            parameters:
                - name: SignInRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/AuthenticationSignInRequestBody'
                    required:
                        - firebaseIdToken
            responses:
                "200":
                    description: 登入完成
                "400":
                    description: token 錯誤
                    schema:
                        $ref: '#/definitions/AuthenticationSignInTokenErrorResponseBody'
            schemes:
                - http
definitions:
    AuthenticationSignInRequestBody:
        title: AuthenticationSignInRequestBody
        type: object
        properties:
            firebaseIdToken:
                type: string
                description: 名稱
                example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.e30.Et9HFtf9R3GEMA0IICOfFMVXY7kkTX1wr4qCyhIf58U
                minLength: 100
        example:
            firebaseIdToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.e30.Et9HFtf9R3GEMA0IICOfFMVXY7kkTX1wr4qCyhIf58U
        required:
            - firebaseIdToken
    AuthenticationSignInTokenErrorResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: SignIn_token_error_Response_Body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
